"""add screenshot status

Revision ID: f9715c438d0b
Revises: 67779fdc8213
Create Date: 2026-07-16 15:26:32.018326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9715c438d0b'
down_revision: Union[str, Sequence[str], None] = '67779fdc8213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = sa.Enum('PENDING', 'COMPLETED', 'FAILED',
    name='screenshotstatus')
    status_enum.create(op.get_bind())
    op.add_column('screenshots', sa.Column('status', status_enum, nullable=False, server_default='PENDING'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenshots', 'status')
    sa.Enum(name='screenshotstatus').drop(op.get_bind())
    # ### end Alembic commands ###
